package com.doing.englishbox.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.doing.englishbox.data.entity.AboutItem;
import com.doing.englishbox.data.entity.Chinese;
import com.doing.englishbox.data.entity.BoxItem;
import com.doing.englishbox.data.entity.Sentence;

import com.doing.englishbox.data.greendao.AboutItemDao;
import com.doing.englishbox.data.greendao.ChineseDao;
import com.doing.englishbox.data.greendao.BoxItemDao;
import com.doing.englishbox.data.greendao.SentenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aboutItemDaoConfig;
    private final DaoConfig chineseDaoConfig;
    private final DaoConfig boxItemDaoConfig;
    private final DaoConfig sentenceDaoConfig;

    private final AboutItemDao aboutItemDao;
    private final ChineseDao chineseDao;
    private final BoxItemDao boxItemDao;
    private final SentenceDao sentenceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aboutItemDaoConfig = daoConfigMap.get(AboutItemDao.class).clone();
        aboutItemDaoConfig.initIdentityScope(type);

        chineseDaoConfig = daoConfigMap.get(ChineseDao.class).clone();
        chineseDaoConfig.initIdentityScope(type);

        boxItemDaoConfig = daoConfigMap.get(BoxItemDao.class).clone();
        boxItemDaoConfig.initIdentityScope(type);

        sentenceDaoConfig = daoConfigMap.get(SentenceDao.class).clone();
        sentenceDaoConfig.initIdentityScope(type);

        aboutItemDao = new AboutItemDao(aboutItemDaoConfig, this);
        chineseDao = new ChineseDao(chineseDaoConfig, this);
        boxItemDao = new BoxItemDao(boxItemDaoConfig, this);
        sentenceDao = new SentenceDao(sentenceDaoConfig, this);

        registerDao(AboutItem.class, aboutItemDao);
        registerDao(Chinese.class, chineseDao);
        registerDao(BoxItem.class, boxItemDao);
        registerDao(Sentence.class, sentenceDao);
    }
    
    public void clear() {
        aboutItemDaoConfig.clearIdentityScope();
        chineseDaoConfig.clearIdentityScope();
        boxItemDaoConfig.clearIdentityScope();
        sentenceDaoConfig.clearIdentityScope();
    }

    public AboutItemDao getAboutItemDao() {
        return aboutItemDao;
    }

    public ChineseDao getChineseDao() {
        return chineseDao;
    }

    public BoxItemDao getBoxItemDao() {
        return boxItemDao;
    }

    public SentenceDao getSentenceDao() {
        return sentenceDao;
    }

}
